from math import *
a = int(input("Введите значение переменной a: "))
b = int(input("Введите значение переменной b: "))
print(f"{a} + {b} = {a + b}")
print(f"{a} - {b} = {a - b}")
print(f"{a} * {b} = {a * b}")
print(f"{a} / {b} = {a / b}")
print(f"{a} // {b} = {a // b}")
print(f"{a} % {b} = {a % b}")
print(f"{a} ** 2 = {a ** 2}")
print(f"{b} ** 2 = {b ** 2}")
print(f"sqrt({a}) = {sqrt(a)}")
print(f"sqrt({b}) = {sqrt(b)}")
print(-a, -b)
print(f"log({a}) = {log(a)}")
print(f"log({b}) = {log(b)}")
print(oct(a), oct(b))
print(hex(a), hex(b))
